'on':
  issues:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Create a jekyll post from an issue
        uses: yoshum/issue-to-jekyll-post@v0
        with:
          post_dir: _posts
          update_filename: true
          layout: post
          timezone: Europe/Berlin
        run: |
          git add .
          git commit -m "add a post"
          git push
